// BULLET ARMOR VALUES FOR DIFFERENT CLASSES OF ARMOR
/// LEVEL I PROTECTION, SIMILIAR TO A SEC VEST
#define BULLET_ARMOR_I 30
/// LEVEL II PROTECTION, SIMILIAR TO A UN VEST
#define BULLET_ARMOR_II 50
/// LEVEL III PROTECTION, BETWEEN LEVEL II AND IV (this is one of the comments of all time)
#define BULLET_ARMOR_III 75
/// LEVEL IV PROTECTION, SIMILAR TO THE VAL ARMOR
#define BULLET_ARMOR_IV 90
/// LEVEL V PROTECTION, FOR THE STRONGEST OF THE STRONG BULLET VESTS
#define BULLET_ARMOR_V 120
